# Generated by Django 5.1.4 on 2024-12-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_brand_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='brand/'),
        ),
    ]
